-- ==========================================================
-- Mis Finanzas - Tabla: debts
-- Ejecutar en el editor SQL del proyecto Supabase.
--
-- Orden: requiere 001_categories.sql y 002_transactions.sql
--
-- IMPORTANTE: si ya habías creado `debts` con la versión anterior
-- de este script (sin cuotas), ejecuta antes:
--   drop table if exists public.debts cascade;
--
-- Es idempotente: puede ejecutarse las veces que sea.
-- ==========================================================

-- Trigger para mantener updated_at actualizado.
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  description text not null default '',
  capital_amount double precision not null check (capital_amount > 0),
  cuotas integer not null check (cuotas > 0),
  cuota_amount double precision not null check (cuota_amount > 0),
  category_id bigint not null references public.categories (id) on delete restrict,
  payment_method text not null default 'efectivo',
  date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists debts_user_id_idx on public.debts (user_id);
create index if not exists debts_user_id_date_idx on public.debts (user_id, date);

alter table public.debts enable row level security;

drop policy if exists "debts_select_own" on public.debts;
create policy "debts_select_own" on public.debts
  for select using (auth.uid() = user_id);
drop policy if exists "debts_insert_own" on public.debts;
create policy "debts_insert_own" on public.debts
  for insert with check (auth.uid() = user_id);
drop policy if exists "debts_update_own" on public.debts;
create policy "debts_update_own" on public.debts
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "debts_delete_own" on public.debts;
create policy "debts_delete_own" on public.debts
  for delete using (auth.uid() = user_id);

drop trigger if exists debts_set_updated_at on public.debts;
create trigger debts_set_updated_at
  before update on public.debts
  for each row execute function public.handle_updated_at();
