-- ==========================================================
-- Mis Finanzas - Tabla: debt_installments (cuotas)
-- Ejecutar en el editor SQL del proyecto Supabase.
--
-- Orden: requiere 001_categories.sql, 002_transactions.sql
--        y 003_debts.sql
--
-- Cada cuota es un egreso dentro de su mes, por eso la proyección
-- de la deuda hacia los meses futuros.
--
-- Es idempotente: puede ejecutarse las veces que sea.
-- ==========================================================

create table if not exists public.debt_installments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  debt_id bigint not null references public.debts (id) on delete cascade,
  number integer not null check (number > 0),
  amount double precision not null check (amount > 0),
  date date not null,
  transaction_id bigint references public.transactions (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists debt_installments_user_id_idx on public.debt_installments (user_id);
create index if not exists debt_installments_debt_id_idx on public.debt_installments (debt_id);
create index if not exists debt_installments_user_id_date_idx on public.debt_installments (user_id, date);
create unique index if not exists debt_installments_debt_number_idx on public.debt_installments (debt_id, number);
create unique index if not exists debt_installments_transaction_id_idx on public.debt_installments (transaction_id);

alter table public.debt_installments enable row level security;

drop policy if exists "debt_installments_select_own" on public.debt_installments;
create policy "debt_installments_select_own" on public.debt_installments
  for select using (auth.uid() = user_id);
drop policy if exists "debt_installments_insert_own" on public.debt_installments;
create policy "debt_installments_insert_own" on public.debt_installments
  for insert with check (auth.uid() = user_id);
drop policy if exists "debt_installments_update_own" on public.debt_installments;
create policy "debt_installments_update_own" on public.debt_installments
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "debt_installments_delete_own" on public.debt_installments;
create policy "debt_installments_delete_own" on public.debt_installments
  for delete using (auth.uid() = user_id);
