-- ==========================================================
-- Mis Finanzas - Tabla: goals
-- Ejecutar en el editor SQL del proyecto Supabase.
--
-- Orden: sin dependencias (puede ejecutarse al final).
--
-- Es idempotente: puede ejecutarse las veces que sea.
-- ==========================================================

-- Trigger para mantener updated_at actualizado.
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  description text not null default '',
  target_amount double precision not null check (target_amount > 0),
  saved_amount double precision not null default 0 check (saved_amount >= 0),
  target_date date,
  icon text not null default 'target',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists goals_user_id_idx on public.goals (user_id);

alter table public.goals enable row level security;

drop policy if exists "goals_select_own" on public.goals;
create policy "goals_select_own" on public.goals
  for select using (auth.uid() = user_id);
drop policy if exists "goals_insert_own" on public.goals;
create policy "goals_insert_own" on public.goals
  for insert with check (auth.uid() = user_id);
drop policy if exists "goals_update_own" on public.goals;
create policy "goals_update_own" on public.goals
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "goals_delete_own" on public.goals;
create policy "goals_delete_own" on public.goals
  for delete using (auth.uid() = user_id);

drop trigger if exists goals_set_updated_at on public.goals;
create trigger goals_set_updated_at
  before update on public.goals
  for each row execute function public.handle_updated_at();
